import { useMachine } from '@xstate/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { todosMachine } from '../machines/todoAppMachine'


export default function Home() {
  const [state, send] = useMachine(todosMachine)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div>
          {JSON.stringify(state.value)}
          <button onClick={() => {send("Todos loaded"); 
          }
          }> Todos loaded</button>
          <button onClick={() => {send("Loading Todos failed");
          }}
          > Loading Todos Failed</button>



          
        </div>
      </main>
    </>
  )
}
